Report compilation summary

diff --git a/farm-compile b/farm-compile
--- a/farm-compile
+++ b/farm-compile
@@ -13,6 +13,7 @@ if test -d utils; then
 	target=driver
 fi
 
+error=
 for bintree in $farmbin/*; do
 	arch=
 	if test -r $bintree/configured-i386; then
@@ -34,7 +35,16 @@ for bintree in $farmbin/*; do
 		mv $log $log-ok
 		echo -e "\e[32mOK\e[0m"
 	else
+		error=1
 		mv $log $log-error
 		echo -e "\e[31mERROR\e[0m"
 	fi
 done
+
+if test -z "$error"; then
+		echo -e "\e[32mAll OK\e[0m"
+		exit 0
+	else
+		echo -e "\e[31mErrors found\e[0m"
+		exit 1
+fi
