Show summary for farm-config32 and farm-config64, return 1 for errors

diff --git a/farm-config32 b/farm-config32
--- a/farm-config32
+++ b/farm-config32
@@ -6,6 +6,7 @@ set -e
 arch=i386
 ccflags=-m32
 
+error=
 for srctree in $(ls -d $farmsrc/* | sort -V); do
 	test -d $srctree/Documentation || continue
 	bintree=$farmbin/$(basename $srctree)-$arch
@@ -34,8 +35,17 @@ for srctree in $(ls -d $farmsrc/* | sort -V); do
 		date > $bintree/configured-$arch
 		echo -e "\e[32mOK\e[0m"
 	else
+		error=1
 		cd $srctree
 		mv $bintree $bintree-bad
 		echo -e "\e[31mERROR\e[0m"
 	fi
 done
+
+if test -z "$error"; then
+		echo -e "\e[32mAll OK\e[0m"
+		exit 0
+	else
+		echo -e "\e[31mErrors found\e[0m"
+		exit 1
+fi
